name: 'trend_radar'
version: '1.0.0'

profile: 'trend_radar'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  trend_radar:
    bronze:
      +materialized: view
    silver:
      +materialized: table
    gold:
      +materialized: table
