"""add companies, seniority, favorites

Revision ID: de5cbf463a0a
Revises: 91af92df7c28
Create Date: 2026-07-25 19:10:54.295132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'de5cbf463a0a'
down_revision: Union[str, None] = '91af92df7c28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('normalized_name', sa.String(length=300), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name', name='uq_company_normalized_name')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('seniority', sa.String(length=50), nullable=True))
        batch_op.add_column(
            sa.Column('is_favorite', sa.Boolean(), nullable=False, server_default=sa.text('0'))
        )
        batch_op.create_foreign_key(
            'fk_contacts_company_id_companies', 'companies', ['company_id'], ['id'], ondelete='SET NULL'
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_contacts_company_id_companies', type_='foreignkey')
        batch_op.drop_column('is_favorite')
        batch_op.drop_column('seniority')
        batch_op.drop_column('company_id')

    op.drop_table('companies')
    # ### end Alembic commands ###
