name: 'musicdna'
version: '1.0.0'
config-version: 2

profile: 'musicdna'

model-paths: ['models']
test-paths:  ['tests']
target-path: 'target'
clean-targets: ['target']

models:
  musicdna:
    marts:
      +materialized: view
